version: '3'

services:
  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data:/var/www/html
  caddy:
    image: caddy:latest
    volumes:
      - ./caddy/Caddyfile.json:/etc/caddy/Caddyfile.json
    expose:
      - 80
    ports:
      - 8888:80
    entrypoint: ["caddy", "run", "--config", "/etc/caddy/Caddyfile.json"]
  uwsgi:
    build: uwsgi/
    expose:
      - 8002